import { Box, Code, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <Box as="main" className={styles.main}>
          <Heading as="h1" className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </Heading>

          <Text className={styles.description}>
            Get started by editing{" "}
            <Code className={styles.code}>pages/index.tsx</Code>
          </Text>

          <Box className={styles.grid}>
            <Box as="a" href="https://nextjs.org/docs" className={styles.card}>
              <Heading as="h2">Documentation &rarr;</Heading>
              <Text>
                Find in-depth information about Next.js features and API.
              </Text>
            </Box>

            <Box as="a" href="https://nextjs.org/learn" className={styles.card}>
              <Heading as="h2">Learn &rarr;</Heading>
              <Text>
                Learn about Next.js in an interactive course with quizzes!
              </Text>
            </Box>

            <Box
              as="a"
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <Heading as="h2">Examples &rarr;</Heading>
              <Text>
                Discover and deploy boilerplate example Next.js projects.
              </Text>
            </Box>

            <Box
              as="a"
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <Heading as="h2">Deploy &rarr;</Heading>
              <Text>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </Text>
            </Box>
          </Box>
        </Box>
      </body>

      <footer className={styles.footer}>
        <Box
          as="a"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Box>
      </footer>
    </Box>
  );
};

export default Home;
